config/routes.rb
Pomhub::Application.routes.draw do
  devise_for :users

  resources :users do
    resources :pomodoros do
      collection do
        post :start
        post :stop
      end
    end
  end

  resources :organizations do
    resources :memberships do
      member do
        put :approve
        put :reject
        post :request_membership
      end
    end
  end

  match '/auth/:provider/callback', to: 'sessions#create'
  match '/auth/failure', to: 'users#index'

  root :to => 'users#index'

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base

  belongs_to :user

  def self.find_or_create_by_hash(auth_hash)
    auth = self.where({
      :provider => auth_hash['provider'],
      :provider_id => auth_hash['info']['uid']
    }).first
    unless auth and auth.user then
      auth ||= self.new({
        :provider => auth_hash['provider'],
        :provider_id => auth_hash['info']['uid']
      })
      user = User.find_or_create_by_email(auth_hash['info']['email'])
#      user.name = auth_hash['info']['name']
      user.username = auth_hash['info']['nickname']
      auth.user = user
      auth.save!
    end

    auth
  end

end

app/models/membership.rb
class Membership < ActiveRecord::Base
  STATUSES = {
    :pending_user => 0,
    :pending_org => 1,
    :active => 2
  }

  belongs_to :organization
  belongs_to :user

  validates_presence_of :user_id
  validates_uniqueness_of :user_id, :scope => :organization_id

  scope :pending, where('status != ?', STATUSES[:active])
  scope :pending_user, where(:status => STATUSES[:pending_user])
  scope :pending_org, where(:status => STATUSES[:pending_org])
  scope :active, where(:status => STATUSES[:active])

  def friendly_status # TODO: decorate
    STATUSES.invert[status]
  end

  attr_accessor :email
  before_validation :fetch_user_by_email
  def fetch_user_by_email
    unless self.user or self.user_id then
      self.user = User.find_or_create_by_email(self.email)
      raise Exception unless self.user
    end
  end

  after_create :send_invitation_approval
  def send_email_notification
    if email then

    end
  end

  after_update :send_invitation_update
  def send_invitation_update

  end
end

app/models/organization.rb
class Organization < ActiveRecord::Base

  has_many :memberships
  has_many :users, :through => :memberships

  belongs_to :owner, :class_name => 'User'

  after_create :create_owner_membership!
  def create_owner_membership!
    Membership.create({
      :user => owner,
      :organization => self,
      :status => Membership::STATUSES[:active]
    })
  end

end

app/models/pomodoro.rb
class Pomodoro < ActiveRecord::Base

  belongs_to :user
  scope :running, where(:stopped_at => nil)

  def time_left
    (started_at + user.pomodoro_length_in_minutes * 1.minute) - Time.now
  end

end

app/models/user.rb
require 'digest/md5'


class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :token_authenticatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :public, :pomodoro_length_in_minutes

  before_save :ensure_authentication_token

  scope :public, where(:public => true)

  has_many :pomodoros
  has_many :authentications

  has_many :owned_organizations, :class_name => 'Organization', :foreign_key => 'owner_id'
  has_many :memberships
  has_many :organizations, :through => :memberships

  validates_presence_of :email
  validates_length_of :email, :in => 2..128
  # validates_format_of email not suck # TODO

  def github_projects
    Rails.cache.fetch("/users/#{self.id}/github_projects", :expires_in => 1.day) {
      gh = Github.new(authentications.where(:provider => 'github').first.provider_token)
      gh.repos
    }
  end

  # This stuff isn't in the decorator, because it's used for current_user, which isn't decorated.
  def to_s
    username || sanitized_email || 'Anonymous'
  end

  def sanitized_email
    email.split('@').first
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController

  before_filter :authenticate_user!

  respond_to :html

  def create
    @organization = current_user.owned_organizations.find(params[:organization_id])
    @membership = @organization.memberships.create(params[:membership])
    respond_with(@organization)
  end

  def request_membership
    @organization = Organization.find(params[:organization_id])
    @membership = Membership.create({
      :user => current_user,
      :organization => @organization,
      :status => Membership::STATUSES[:pending_org]
    })

    respond_with(@membership, :location => @organization)
  end

  def approve
    @organization = Organization.find(params[:organization_id])
    @membership = find_manageable_membership

    @membership.status = Membership::STATUSES[:active]
    @membership.save
    respond_with(@organization)
  end

  def reject
    @organization = Organization.find(params[:organization_id])
    @membership = find_manageable_membership
    @membership.destroy

    respond_with(@organization)
  end

  private

  def find_manageable_membership
    @membership = @organization.memberships.pending.find(params[:id])

    case @membership.status
    when Membership::STATUSES[:pending_user]
      raise ActiveRecord::NotFound unless @membership.user == current_user
    when Membership::STATUSES[:pending_org]
      raise ActiveRecord::NotFound unless current_user.owned_organizations.find(@organization.id)
    end

    @membership
  end

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  before_filter :authenticate_user!

  respond_to :html

  def index
    @organizations = Organization.public.all
  end

  def show
    @organization = Organization.find(params[:id])
    @users = UserDecorator.decorate(@organization.memberships.active.collect(&:user).flatten)
  end

  def new
    @organization = current_user.owned_organizations.build
  end

  def create
    @organization = current_user.owned_organizations.create(params[:organization])
    respond_with(@organization)
  end

  def edit
    @organization = current_user.owned_organizations.find(params[:id])
    respond_with(@organization)
  end

  def update
    @organization = current_user.owned_organizations.find(params[:id])
    @organization.update_attributes(params[:organization])
    respond_with(@organization)
  end

end

app/controllers/pomodoros_controller.rb
class PomodorosController < ApplicationController

  skip_before_filter :verify_authenticity_token

  before_filter :authenticate_user!

  respond_to :html

  def start
    @pomodoro = current_user.pomodoros.create(params[:pomodoro].merge({
      :started_at => Time.now
    }))
    respond_with([current_user, @pomodoro])
  end

  def stop
    @pomodoro = current_user.pomodoros.running.last
    @pomodoro.stopped_at = Time.now
    @pomodoro.save
    respond_with([current_user, @pomodoro])
  end

  def new
    @pomodoro = current_user.pomodoros.build
    respond_with(@pomodoro)
  end

  def create
    @pomodoro = current_user.pomodoros.create(params[:pomodoro].merge({
      :started_at => Time.now
    }))
    respond_with(current_user)
  end

  def destroy
    @pomodoro = current_user.pomodoros.find(params[:id])
    @pomodoro.destroy

    respond_with(current_user)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @auth = Authentication.find_or_create_by_hash(auth_hash)

    if @auth then
      @auth.provider_token = auth_hash['credentials']['token']
      @auth.raw_details = auth_hash
      @auth.save

      sign_in(@auth.user)
      flash[:notice] = I18n.t('auth.success')
    else
      flash[:notice] = I18n.t('auth.failed')
    end
    redirect_to @auth.user
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!, :except => [:index]

  respond_to :html

  def index
    @users = UserDecorator.decorate(User.public.all)
  end

  def show
    @user = UserDecorator.decorate(User.find(params[:id]))
  end

  def edit
    @user = UserDecorator.decorate(current_user)
  end

  def update
    @user = UserDecorator.decorate(current_user)
    @user.update_attributes(params[:user])
    respond_with(@user)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pomhub</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700' rel='stylesheet' type='text/css'>
</head>
<body>

  <header>
    <h1><a href="/">PomHub</a>
    <% if @organization and @organization.persisted? then %>
    <a href="<%=organization_path(@organization)%>">&mdash; <%=@organization.name %></a>
    <% end %>
    </h1>

    <% if current_user then %>
    <div class="organizations-nav">
      <% current_user.memberships.active.each {|membership| %>
        <%=link_to membership.organization.name, membership.organization %>
      <% } %>
    </div>
    <% end %>

    <%= render :partial => '/users/authentication' %>
  </header>

  <%= yield %>

  <footer>
    <div class="social_buttons">

    </div>
    <div class="legal">
      &copy; 2012 <a href="http://twitter.com/adrianpike">Adrian Pike</a>, with a <a href="https://github.com/carnesmedia/pomhub/blob/master/README.md">lotta help from my friends.</a>
  </footer>

</body>
</html>

app/views/organizations/_form.html.erb
<%=simple_form_for @organization do |f| %>

  <%=f.input :name %>
  <%=f.input :public %>

  <%=f.button :submit %>
<% end %>

app/views/organizations/_manage.html.erb
<% if @organization.memberships.pending_user.size > 0 then %>
<div class="pending-invitations">
  Waiting for approval from:
  <% @organization.memberships.pending_user.each {|membership| %>
    <%=link_to membership.user, membership.user %>
  <% } %>
</div>
<% end %>

<% if @organization.memberships.pending_org.size > 0 then %>
<div class="pending-invitations">
  <strong>Your organization has pending invitations.</strong>
  <ul>
  <% @organization.memberships.pending_org.each {|membership| %>
    <li><%=link_to membership.user.to_s, membership.user %>

      <%=link_to 'Approve', approve_organization_membership_path(membership.organization, membership), :method => "put" %>
      <%=link_to 'Reject', reject_organization_membership_path(membership.organization, membership), :method => "put" %>
    </li>
  <% } %>
  </ul>
</div>
<% end %>

app/views/organizations/edit.html.erb
<%= render :partial => '/organizations/form' %>

<h2>Members</h2>
<ul>
<% @organization.memberships.each{|mship| %>
  <li><%=mship.user.to_s%> &mdash; <%=mship.friendly_status%></li>
<% } %>
</ul>

<h2>Invite Member</h2>
<%=simple_form_for [@organization,@organization.memberships.build] do |f| %>

  <%=f.input :email %>

  <%=f.button :submit %>
<% end %>

app/views/organizations/new.html.erb
<%= render :partial => '/organizations/form' %>

app/views/organizations/show.html.erb
<% if current_user == @organization.owner then %>
  <%=render :partial => '/organizations/manage' %>
<% end %>

<% unless current_user.memberships.where(:organization_id => @organization.id).count > 0 then %>
  <%=link_to 'Request Membership', request_membership_organization_membership_path(@organization), :method => :post %>
<% end %>

<% if @organization.public || current_user.memberships.where(:organization_id => @organization.id).active.count > 0 then %>

  <ul class="userlist">
    <%= render @users %>
  </ul>

<% else %>

  <p>You're not a member of this organization.</p>

<% end %>

app/views/pomodoros/_pomodoro.html.erb
<div class="pomodoro">
<%=I18n.l(pomodoro.started_at)%> &mdash; <%=I18n.l(pomodoro.stopped_at) rescue 'N/A'%>
<p><%=pomodoro.githubbed_description%></p>

<% if current_user == pomodoro.user then %>
  <%=link_to 'Delete', user_pomodoro_path(current_user, pomodoro), :method => :delete%>
<% end %>
</div>

app/views/pomodoros/new.html.erb
<%=simple_form_for [current_user,@pomodoro] do |f| %>

  <%=f.input :description %>

  <%=f.button :submit %>
<% end %>

app/views/users/_authentication.html.erb
<div class="authentication">
<% if current_user then %>
  <%=link_to current_user, edit_user_path(current_user) %>
  <%=link_to 'Sign out', destroy_user_session_path %>
<% else %>
  <%=link_to 'Sign in with Github', '/auth/github' %>
  <%=link_to 'Sign in with Email', '/users/sign_in' %>
<% end %>
</div>

app/views/users/_manage.html.erb
<% if current_user.memberships.pending_user.size > 0 then %>
<div class="pending-invitations">
  <strong>You have pending organization invitations.</strong>
  <ul>
  <% current_user.memberships.pending_user.each {|membership| %>
    <li><%=link_to membership.organization.name, membership.organization %>

      <%=link_to 'Approve', approve_organization_membership_path(membership.organization, membership), :method => "put" %>
      <%=link_to 'Reject', reject_organization_membership_path(membership.organization, membership), :method => "put" %>
    </li>
  <% } %>
  </ul>
</div>
<% end %>

app/views/users/_user.html.erb
<li class="user" id="<%=dom_id(user)%>">
  <a class="avatar-link" href="<%=url_for(user)%>">
    <img src="<%=user.avatar%>" alt="<%=user%>">
  </a>
  <div class="user-info">
    <h3 data-pom-start=<%=raw user.active_pomodoro.try(:started_at).to_json%> data-pom-length-in-minutes=<%=raw user.pomodoro_length_in_minutes.to_s.to_json%>><%=user.time_left%></h3>
    <a href="<%=url_for(user)%>" class="name-link">
      <strong><%=user%></strong>
    </a>
  </div>
  <p><%=user.pomodoro_description%></p>
</li>

app/views/users/_welcome.html.erb
<div class="setup">
  <h2>Welcome to Pomhub!</h2>
  <p>Let's get you up and running as quickly as possible. PomHub is intended to be integrated with a third-party Pomodoro timer, such as Pomodoro.app, but you can easily use PomHub as a standalone timer. Once your first Pomodoro has shown up, these setup steps will go away. You can always get back to them in the help.</p>

  <p>By default, all of your Pomodoros are private, and can only be seen by yourself and organizations you join. You can easily change this in your settings.</p>
  <p>If you haven't already, make sure and link your Github, so we can automatically reference repositories or issues you mention.</p>

  <h3>Custom Integration</h3>
  <p>Your API token is: <strong><%=@user.authentication_token%></strong></p>

  <h3>Pomodoro.app</h3>
  <p>Pomodoro.app is a great piece of software. To link Pomodoro.app to PomHub, go into your Pomodoro Preferences, into Scripts, and put the following snippets into Start and End, respectively.</p>
  <strong>Start</strong>
  <pre>
    do shell script "curl -d 'auth_token=<%=@user.authentication_token%>&amp;pomodoro[description]=$pomodoroName' <%=start_user_pomodoros_url(@user)%>"</pre>
  <strong>End</strong>
  <pre>
    do shell script "curl -d 'auth_token=<%=@user.authentication_token%>&amp;pomodoro[description]=$pomodoroName' <%=stop_user_pomodoros_url(@user)%>"</pre>
</div>

app/views/users/edit.html.erb
<%=simple_form_for @user do |f| %>

  <%=f.input :public %>
  <%=f.input :pomodoro_length_in_minutes %>

  <%=f.button :submit%>
<% end %>

<h2>Manage My Organizations</h2>
<ul>
<% current_user.owned_organizations.each{|org| %>
  <li><%=link_to org.name, edit_organization_path(org) %></li>
<% } %>
</ul>
<%=link_to 'New Organization', new_organization_path %>
</div>

app/views/users/index.html.erb
<ul class="userlist">
  <%= render @users %>
</ul>

app/views/users/show.html.erb
<% if current_user == @user.model then %>
  <%=render :partial => '/users/manage' %>
<% end %>

<article id="<%=dom_id(@user)%>" class="user">

  <h1><img src="<%=@user.avatar%>" alt="<%=@user%>"><%=@user%></h1>
  <% if current_user == @user.model then %>
    <%=render :partial => '/users/welcome' if @user.pomodoros.count == 0 %>
    <%=link_to 'Start a Pomodoro!', new_user_pomodoro_path(current_user), :class => 'button' %>
  <% end %>

  <%= render PomodoroDecorator.decorate(@user.pomodoros.order('created_at desc')) %>

</article>